name: main

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x

      - name: Prettier formatting check
        run: npx prettier --check main.js

      - name: Check that dependencies are compatible with MIT license
        run: npx license-checker --onlyAllow 'MIT;BSD;Apache-2.0;CC0-1.0;CC-BY-3.0;CC-BY-4.0;ISC;Hippocratic-2.1;MPL-2.0;ODC-By-1.0;WTFPL;Unlicense'

  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x

      - name: Build static web app bundle
        run: |
          npm install
          npm run build
          cp -r data dist

      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
