name: main

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x

      - name: Prettier formatting check
        run: npx prettier --check src

      - name: Check that dependencies are compatible with MIT license
        run: npx license-checker --onlyAllow 'MIT;BSD;Apache-2.0;CC0-1.0;CC-BY-3.0;CC-BY-4.0;ISC;Hippocratic-2.1;MPL-2.0;ODC-By-1.0;WTFPL;Unlicense'

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x

      - name: Build static web app bundle
        run: |
          npm run build
          cp -r data dist


      - name: Create a new commit to gh-pages
        run: |
          git add --force dist
          git -c user.name="GitHub Actions" -c user.email="actions@github.com" commit -m "Apply automatic changes" --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          git subtree split --prefix dist -b gh-pages
          git push --force origin gh-pages
